# Generated by Django 4.0.2 on 2022-03-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('match_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('review', 'In Review'), ('completed', 'Completed'), ('refund', 'Refunded'), ('abandoned', 'Abandoned')], default='upcoming', max_length=20)),
                ('is_lineups_out', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='application.teams')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='application.teams')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.series')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
