# Generated by Django 4.0.2 on 2022-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
