# Generated by Django 4.0.2 on 2022-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_players_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('wk', 'WK'), ('bat', 'BAT'), ('ar', 'AR'), ('bowl', 'BOWL')], max_length=10)),
                ('image', models.ImageField(upload_to='images/players')),
                ('nationality', models.CharField(max_length=256)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.sports')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
