# Generated by Django 4.0.2 on 2022-03-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_cricketplayers_delete_players'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CricketPlayers',
            new_name='Players',
        ),
    ]
