# Generated by Django 4.0.2 on 2022-04-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rename_cricketplayers_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='select_players',
            field=models.ManyToManyField(to='application.Players'),
        ),
    ]
