# Generated by Django 4.0.2 on 2022-04-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_teams_select_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='short_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='TeamPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.teams')),
            ],
            options={
                'verbose_name': 'Player of Team',
                'verbose_name_plural': 'Players of Teams',
            },
        ),
    ]
