# Generated by Django 4.0.2 on 2022-04-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_createplayersformatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatePlayersForMatch',
            new_name='CricketPlayersForMatch',
        ),
    ]
