# Generated by Django 4.0.2 on 2022-04-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_createplayersformatch_cricketplayersformatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketplayersformatch',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cricketplayersformatch',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
    ]
