# Generated by Django 4.0.2 on 2022-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_cricketplayersformatch_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketplayersformatch',
            name='no_of_shares_for_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cricketplayersformatch',
            name='no_of_shares_for_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cricketplayersformatch',
            name='shares_available_for_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cricketplayersformatch',
            name='shares_available_for_sell',
            field=models.IntegerField(default=0),
        ),
    ]
